[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'airblade/vim-fugitive'
hook_add = '''
command Gst :Gstatus
command Gdf :Gdiff
command Gbl :Gblame
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
nnoremap <C-p> :FZFFileList<CR>
command! FZFFileList call fzf#run({
 \ 'down': '50%',
 \ 'source': 'find . -type d -name .git -prune -o ! -name .DS_Store',
 \ 'sink': 'e'})
command! -bang -nargs=* Ripgrep
 \ call fzf#vim#grep(
 \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
 \   <bang>0 ? fzf#vim#with_preview('up:60%')
 \           : fzf#vim#with_preview({'options': '--exact --reverse --delimiter : --nth 3..'}, 'right:50%:hidden', '?'),
 \   <bang>0)
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'justinmk/vim-dirvish'
